# Account Inquiry
transaction.account-inquiry.uba-receiver-bank=000004
transaction.account-inquiry.acquiring-inst-id=some_value
transaction.account-inquiry.mti=some_value
transaction.account-inquiry.processing-code.fincale=some_value
transaction.account-inquiry.processing-code.nip=some_value
transaction.account-inquiry.target-system.cor=some_value
transaction.account-inquiry.target-system.nip=some_value

# Balance Inquiry
transaction.balance-inquiry.processing-code.gtp=some_value
transaction.balance-inquiry.processing-code.fincale=some_value
transaction.balance-inquiry.target-system.gtp=some_value
transaction.balance-inquiry.target-system.cor=some_value
